# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Coding Cups
email: 
description: I am just learning... 
# baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://dumpofmemory.github.io" # the base hostname & protocol for your site
twitter_username: enter_the_v0id
github_username:  dumpofmemory

# Build settings
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
# highlighter: rouge
# highlighter: none


theme: jekyll-theme-cayman